export enum CharacterList {
  Alchemist = 'Alchemist',
  DragonMage = 'DragonMage',
  Illusionist = 'Illusionist',
  Knight = 'Knight',
  Overlord = 'Overlord',
  Mascot = 'Mascot',
  // Vampire = 'Vampire',
  // Templar = 'Templar',
  // Witch = 'Witch',
  // Fighter = 'Fighter',
  // Pyromancer = 'Pyromancer',
  // Healer = 'Healer',
  // Homunculus = 'Homunculus',
  // Trapper = 'Trapper',
  // Summoner = 'Summoner',
  // Scientist = 'Scientist',
  // Priestess = 'Priestess',
  // Assassin = 'Assassin',
  // Gunner = 'Gunner',
  // Doppelganger = 'Doppelganger',
  // Oracle = 'Oracle',
  // Berserker = 'Berserker',
  // Mystic = 'Mystic',
  // Paladin = 'Paladin',
  // Planestalker = 'Planestalker',
}
